name: action-triggered-on-push
on:
  push:
    branches:
      - main
      
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Printt
        run: |
          echo "hello how are you"
