name: test-action-on-branching
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select a test environment
        options:
          - DEV
          - QA
          - STAGE
          - PROD
      test_type:
        required: true
        type: choice
        description: Select a test type
        options:
          - PAYROLL
          - ADDRESSCLEANSE
          - BOTH

jobs:
  branching-tests:
    env:
      TEST_ENV: ${{ github.event.inputs.environment }}
      TEST_TYPE: ${{ github.event.inputs.test_type }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Selected environment
        run: echo "Environment::$TEST_ENV"
      - name: Print Selected test type
        run: echo "Test type::$TEST_TYPE"
      - name: Print test user name
        run: echo "user name::$TEST_USERNAME"
      - name: Print test user pwd
        run: echo "user pwd::$TEST_PASSWORD"
      - if: env.TEST_ENV == 'DEV' && (env.TEST_TYPE == 'PAYROLL'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for DEV/PAYROLL"
      - if: env.TEST_ENV == 'DEV' && (env.TEST_TYPE == 'ADDRESSCLEANSE'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for DEV/ADDRESSCLEANSE"
      - if: env.TEST_ENV == 'QA' && (env.TEST_TYPE == 'PAYROLL'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for QA/PAYROLL"
      - if: env.TEST_ENV == 'QA' && (env.TEST_TYPE == 'ADDRESSCLEANSE'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for QA/ADDRESSCLEANSE"
      - if: env.TEST_ENV == 'STAGE' && (env.TEST_TYPE == 'PAYROLL'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for STAGE/PAYROLL"
      - if: env.TEST_ENV == 'STAGE' && (env.TEST_TYPE == 'ADDRESSCLEANSE'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for STAGE/ADDRESSCLEANSE"
      - if: env.TEST_ENV == 'PROD' && (env.TEST_TYPE == 'PAYROLL'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for PROD/PAYROLL"
      - if: env.TEST_ENV == 'PROD' && (env.TEST_TYPE == 'ADDRESSCLEANSE'
          || env.TEST_TYPE == 'BOTH')
        name: Run tests in Dev environment for test type PAYROLL/BOTH
        run: |
          echo "Run for PROD/ADDRESSCLEANSE"
